# Generated by Django 4.1.12 on 2024-04-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmstore',
            name='image',
        ),
    ]
